//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class allFan
    {
        public string username { get; set; }
        public string password { get; set; }
        public string Name { get; set; }
        public string National_ID { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
